# Generated by Django 2.2.2 on 2021-03-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='income_date',
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('expense', models.CharField(max_length=50)),
                ('expense_amount', models.IntegerField()),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Income')),
            ],
        ),
    ]
